name: Update File

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update File
        run: |
          sed -i "s/Last updated: .*/Last updated: $(date '+%Y-%m-%d %H:%M:%S')/" UPDATE.md
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add UPDATE.md
          git commit -m "Update file with current date and time"
          git push https://$GH_TOKEN@github.com/Fyphen1223/MK8DXBotDiscord.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
