name: Update File

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update File
        run: |
          sed -i "s/Last updated: .*/Last updated: $(date '+%Y-%m-%d %H:%M:%S')/" UPDATE.md
          git config --global user.email "fyphensub@gmail.com"
          git config --global user.name "Fyphen"
          git add UPDATE.md
          git commit -m "Update file with current date and time"
          git push https://$GH_TOKEN@github.com/Fyphen1223/MK8DX-TA-Bot-Discord.git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
