name: Update File

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          sed -i "s/Last updated: .*/Last updated: $(date '+%Y-%m-%d %H:%M:%S')/" update.md
          git config --global user.email "fyphensub@gmail.com"
          git config --global user.name "Fyphen"
          git commit -am "Update file with current date and time"
          git push
